# Workflow de Continuous Integration focado exclusivamente na execução de testes unitários.
name: Continuous Integration

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '24'
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_SCOPE: juzeniosantos01-6071


jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código-fonte do repositório.
      - name: Checkout
        uses: actions/checkout@v6.1.0

      # Configura a versão do Node.js definida nas variáveis globais.
      - name: Setup Node
        uses: actions/setup-node@v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Habilita o Corepack para disponibilizar o Yarn.
      - name: Enable Corepack
        run: corepack enable

      # Instala as dependências utilizando o yarn.lock para garantir versões consistentes.
      - name: Install Dependencies
        run: yarn install --immutable

      # Executa exclusivamente os testes unitários.
      - name: Run Unit Tests
        run: yarn test


  build-and-deploy:
    name: Build and Deploy Vercel Preview
    needs: [unit-tests]
    runs-on: ubuntu-latest
    outputs:
      preview-url: ${{ steps.deploy.outputs.preview-url }}

    steps:
      # Faz o checkout do código-fonte do repositório.
      - name: Checkout
        uses: actions/checkout@v6.1.0

      # Configura a versão do Node.js definida nas variáveis globais.
      - name: Setup Node
        uses: actions/setup-node@v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Habilita o Corepack para disponibilizar o Yarn.
      - name: Enable Corepack
        run: corepack enable

      # Instala as dependências utilizando o yarn.lock para garantir versões consistentes.
      - name: Install Dependencies
        run: yarn install --immutable

      # Obter as configurações da Vercel
      - name: Pull Vercel Config
        run: yarn vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}

      # Vercel Build
      - name: Vercel Build
        run: yarn vercel build --token=${{ env.VERCEL_TOKEN }}

      # Vercel Deploy preview
      - name: Vercel Deploy preview
        id: deploy
        run: |
          URL="$(yarn --silent vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }} --scope=${{ env.VERCEL_SCOPE }})"
          echo "preview-url=$URL" >> $GITHUB_OUTPUT


  e2e-testes:
    name: E2E Tests
    needs: [build-and-deploy]
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código-fonte do repositório.
      - name: Checkout
        uses: actions/checkout@v6.1.0

      # Configura a versão do Node.js definida nas variáveis globais.
      - name: Setup Node
        uses: actions/setup-node@v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Habilita o Corepack para disponibilizar o Yarn.
      - name: Enable Corepack
        run: corepack enable

      # Instala as dependências utilizando o yarn.lock para garantir versões consistentes.
      - name: Install Dependencies
        run: yarn install --immutable

      # Instalação do chromium
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps chromium

      # Executa exclusivamente os testes e2e.
      - name: Run E2E regression Tests
        run: yarn playwright test playwright/e2e/checkout.spec.ts -g "deve validar mensagens de erro de todos os campos obrigatórios ao submeter formulário em branco"
        env:
          BASE_URL: ${{ needs.build-and-deploy.outputs.preview-url }}

      # Relatório de testes automatizados
      - name: E2E Tests Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v7.0.1
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30


      
